# Generated by Django 5.1.4 on 2024-12-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_fichas',
            name='num',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
