# Generated by Django 5.1.4 on 2024-12-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_t_subtipo_novedad_t_tipo_novedad_t_novedades_descri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_documentos',
            name='ruta',
        ),
        migrations.AddField(
            model_name='t_documentos',
            name='archi',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='t_documentos',
            name='esta',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado')], default='activo', max_length=200),
        ),
    ]
