# Generated by Django 5.1.4 on 2024-12-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_rename_t_perfil_t_perfi_alter_t_perfi_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_actividades',
            new_name='T_acti',
        ),
        migrations.RenameModel(
            old_name='T_actividades_aprendiz',
            new_name='T_acti_apre',
        ),
        migrations.RenameModel(
            old_name='T_actividades_documento',
            new_name='T_acti_descri',
        ),
        migrations.RenameModel(
            old_name='T_actividades_descriptores',
            new_name='T_acti_docu',
        ),
        migrations.RenameModel(
            old_name='T_actividades_ficha',
            new_name='T_acti_ficha',
        ),
        migrations.RenameModel(
            old_name='T_actividades_recurso',
            new_name='T_acti_recu',
        ),
        migrations.RenameModel(
            old_name='T_aprendiz',
            new_name='T_apre',
        ),
        migrations.RenameModel(
            old_name='T_centros_formacion',
            new_name='T_centro_forma',
        ),
        migrations.RenameModel(
            old_name='T_competencias',
            new_name='T_compe',
        ),
        migrations.RenameModel(
            old_name='T_criterios_evaluacion',
            new_name='T_crite_eva',
        ),
        migrations.RenameModel(
            old_name='T_cronogramas',
            new_name='T_crono',
        ),
        migrations.RenameModel(
            old_name='T_descriptores',
            new_name='T_descri',
        ),
        migrations.RenameModel(
            old_name='T_documentos',
            new_name='T_docu',
        ),
        migrations.RenameModel(
            old_name='T_documentos_proceso',
            new_name='T_docu_proce',
        ),
        migrations.RenameModel(
            old_name='T_encuentros',
            new_name='T_encu',
        ),
        migrations.RenameModel(
            old_name='T_guias_documento',
            new_name='T_encu_apre',
        ),
        migrations.RenameModel(
            old_name='T_fases_ficha',
            new_name='T_fase_ficha',
        ),
        migrations.RenameModel(
            old_name='T_fichas',
            new_name='T_ficha',
        ),
        migrations.RenameModel(
            old_name='T_guias',
            new_name='T_guia',
        ),
        migrations.RenameModel(
            old_name='T_encuentros_aprendiz',
            new_name='T_guia_docu',
        ),
        migrations.RenameModel(
            old_name='T_instituciones_educativas',
            new_name='T_insti_edu',
        ),
        migrations.RenameModel(
            old_name='T_instructor',
            new_name='T_instru',
        ),
        migrations.RenameModel(
            old_name='T_novedades',
            new_name='T_nove',
        ),
        migrations.RenameModel(
            old_name='T_novedades_ficha',
            new_name='T_nove_docu',
        ),
        migrations.RenameModel(
            old_name='T_novedades_documentos',
            new_name='T_nove_ficha',
        ),
        migrations.RenameModel(
            old_name='T_programas',
            new_name='T_progra',
        ),
        migrations.RenameModel(
            old_name='T_recursos',
            new_name='T_recu',
        ),
        migrations.RenameModel(
            old_name='T_representante_legal',
            new_name='T_repre_legal',
        ),
        migrations.RenameModel(
            old_name='T_subtipo_novedad',
            new_name='T_subtipo_nove',
        ),
        migrations.RenameModel(
            old_name='T_tipo_novedad',
            new_name='T_tipo_nove',
        ),
        migrations.AlterModelOptions(
            name='t_acti',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_acti_apre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_acti_descri',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_acti_docu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_acti_ficha',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_acti_recu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_admin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_apre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_centro_forma',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_compe',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_crite_eva',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_crono',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_descri',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_docu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_docu_proce',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_encu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_encu_apre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_fase_ficha',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_ficha',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_guia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_guia_docu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_insti_edu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_instru',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_lider',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_nove',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_nove_docu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_nove_ficha',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_progra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_raps',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_recu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_repre_legal',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_subtipo_nove',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t_tipo_nove',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='t_descri',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='t_insti_edu',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='t_nove',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='t_subtipo_nove',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='t_acti_descri',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_acti_docu',
            name='descri',
        ),
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='t_guia_docu',
            name='encu',
        ),
        migrations.RemoveField(
            model_name='t_guia_docu',
            name='estu',
        ),
        migrations.RemoveField(
            model_name='t_nove_docu',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='t_nove_ficha',
            name='docu',
        ),
        migrations.AddField(
            model_name='t_acti_descri',
            name='descri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_descri'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_acti_docu',
            name='docu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_encu_apre',
            name='encu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_encu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_encu_apre',
            name='estu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_guia_docu',
            name='docu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_guia_docu',
            name='guia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_guia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_nove_docu',
            name='docu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_nove_ficha',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='t_acti',
            table='T_acti',
        ),
        migrations.AlterModelTable(
            name='t_acti_apre',
            table='T_acti_apre',
        ),
        migrations.AlterModelTable(
            name='t_acti_descri',
            table='T_acti_descri',
        ),
        migrations.AlterModelTable(
            name='t_acti_docu',
            table='T_acti_docu',
        ),
        migrations.AlterModelTable(
            name='t_acti_ficha',
            table='T_acti_ficha',
        ),
        migrations.AlterModelTable(
            name='t_acti_recu',
            table='T_acti_recu',
        ),
        migrations.AlterModelTable(
            name='t_admin',
            table='T_admin',
        ),
        migrations.AlterModelTable(
            name='t_apre',
            table='T_apre',
        ),
        migrations.AlterModelTable(
            name='t_centro_forma',
            table='T_centro_forma',
        ),
        migrations.AlterModelTable(
            name='t_compe',
            table='T_compe',
        ),
        migrations.AlterModelTable(
            name='t_crite_eva',
            table='T_crite_eva',
        ),
        migrations.AlterModelTable(
            name='t_crono',
            table='T_crono',
        ),
        migrations.AlterModelTable(
            name='t_descri',
            table='T_descri',
        ),
        migrations.AlterModelTable(
            name='t_docu',
            table='T_docu',
        ),
        migrations.AlterModelTable(
            name='t_docu_proce',
            table='T_docu_proce',
        ),
        migrations.AlterModelTable(
            name='t_encu',
            table='T_encu',
        ),
        migrations.AlterModelTable(
            name='t_encu_apre',
            table='T_encu_apre',
        ),
        migrations.AlterModelTable(
            name='t_fase_ficha',
            table='T_fase_ficha',
        ),
        migrations.AlterModelTable(
            name='t_ficha',
            table='T_ficha',
        ),
        migrations.AlterModelTable(
            name='t_guia',
            table='T_guia',
        ),
        migrations.AlterModelTable(
            name='t_guia_docu',
            table='T_guia_docu',
        ),
        migrations.AlterModelTable(
            name='t_insti_edu',
            table='T_insti_edu',
        ),
        migrations.AlterModelTable(
            name='t_instru',
            table='T_instru',
        ),
        migrations.AlterModelTable(
            name='t_lider',
            table='T_lider',
        ),
        migrations.AlterModelTable(
            name='t_nove',
            table='T_nove',
        ),
        migrations.AlterModelTable(
            name='t_nove_docu',
            table='T_nove_docu',
        ),
        migrations.AlterModelTable(
            name='t_nove_ficha',
            table='T_nove_ficha',
        ),
        migrations.AlterModelTable(
            name='t_progra',
            table='T_progra',
        ),
        migrations.AlterModelTable(
            name='t_raps',
            table='T_raps',
        ),
        migrations.AlterModelTable(
            name='t_recu',
            table='T_recu',
        ),
        migrations.AlterModelTable(
            name='t_repre_legal',
            table='T_repre_legal',
        ),
        migrations.AlterModelTable(
            name='t_subtipo_nove',
            table='T_subtipo_nove',
        ),
        migrations.AlterModelTable(
            name='t_tipo_nove',
            table='T_tipo_nove',
        ),
    ]
