# Generated by Django 5.1.4 on 2024-12-20 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_rename_t_actividades_t_acti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_repre_legal',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='t_acti_recu',
            name='acti_docu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_acti_docu'),
        ),
    ]
