# Generated by Django 5.1.4 on 2024-12-20 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_rename_nombre_t_repre_legal_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_perfi',
            new_name='T_perfil',
        ),
        migrations.RenameField(
            model_name='t_perfil',
            old_name='nombre',
            new_name='nom',
        ),
        migrations.AlterModelTable(
            name='t_perfil',
            table='T_perfil',
        ),
    ]
