# Generated by Django 5.1.4 on 2024-12-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_remove_t_acti_ficha_instru_t_ficha_instru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acti',
            name='progra',
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='num_matri',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='progra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_progra'),
            preserve_default=False,
        ),
    ]
