# Generated by Django 5.1.4 on 2024-12-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0011_t_tipo_acti_remove_t_acti_tipo_t_acti_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acti',
            name='guia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_guia'),
            preserve_default=False,
        ),
    ]
