# Generated by Django 5.1.4 on 2024-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0012_t_acti_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acti',
            name='fase',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
