# Generated by Django 5.1.4 on 2024-12-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0014_t_acti_descri'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_raps',
            name='comple',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='t_raps',
            name='fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raps', to='commons.t_fase_ficha'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='T_rap_acti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_acti')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_raps')),
            ],
            options={
                'db_table': 'T_rap_acti',
            },
        ),
    ]
