# Generated by Django 5.1.4 on 2025-01-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0016_alter_t_raps_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_departa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'T_departa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_munici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_munici', models.CharField(max_length=4)),
                ('nom_munici', models.CharField(max_length=200)),
                ('nom_departa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_departa')),
            ],
            options={
                'db_table': 'T_munici',
                'managed': True,
            },
        ),
    ]
