# Generated by Django 5.1.4 on 2024-12-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0017_t_fase_ficha_vige_t_raps_acti'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_raps_ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agre', models.CharField(default='No', max_length=100)),
            ],
            options={
                'db_table': 'T_raps_ficha',
                'managed': True,
            },
        ),
    ]
