# Generated by Django 5.1.4 on 2024-12-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0018_t_raps_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_raps_ficha',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_raps_ficha',
            name='rap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_raps'),
            preserve_default=False,
        ),
    ]
