# Generated by Django 5.1.4 on 2024-12-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0019_t_raps_ficha_ficha_t_raps_ficha_rap'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acti',
            name='raps',
            field=models.ManyToManyField(blank=True, related_name='acti', to='commons.t_raps'),
        ),
        migrations.DeleteModel(
            name='T_rap_acti',
        ),
    ]
