# Generated by Django 5.1.4 on 2024-12-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0023_t_encu_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_encu_apre',
            name='prese',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
