# Generated by Django 5.1.4 on 2024-12-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0025_t_encu_apre_ficha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_encu_apre',
            old_name='estu',
            new_name='apre',
        ),
    ]
