# Generated by Django 5.1.4 on 2024-12-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0027_t_documentfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_documentfolder',
            name='description',
        ),
    ]
