# Generated by Django 5.1.4 on 2024-12-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0029_t_documentfolder_ficha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_DocumentFolder',
        ),
    ]
