# Generated by Django 5.1.4 on 2024-12-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0033_t_documentfolder_ficha_t_documentfolder_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentfolder',
            name='iden',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
