# Generated by Django 5.1.4 on 2024-12-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0036_alter_t_docu_archi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_docu',
            name='archi',
            field=models.FileField(blank=True, null=True, upload_to='documentos'),
        ),
    ]
