# Generated by Django 5.1.4 on 2025-01-04 03:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0037_alter_t_docu_archi'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DocumentFolderAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('link', 'Enlace'), ('carpeta', 'Carpeta')], default='carpeta', max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('iden', models.CharField(blank=True, max_length=200, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commons.t_documentfolderaprendiz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
