# Generated by Django 5.1.4 on 2025-01-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0038_t_documentfolderaprendiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_apre',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha'),
        ),
    ]
