# Generated by Django 5.1.4 on 2025-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0017_t_departa_t_munici'),
        ('commons', '0039_alter_t_apre_ficha'),
    ]

    operations = [
    ]
