# Generated by Django 5.1.4 on 2025-01-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0040_merge_0017_t_departa_t_munici_0039_alter_t_apre_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_insti_edu',
            name='ofi',
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='depa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_departa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='muni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_munici'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='secto',
            field=models.CharField(choices=[('oficial', 'Oficial'), ('noficial', 'No oficial')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
