# Generated by Django 5.1.4 on 2025-01-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0041_remove_t_insti_edu_ofi_t_insti_edu_depa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_insti_edu',
            name='pote_apre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
