# Generated by Django 5.1.4 on 2025-01-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0042_t_insti_edu_pote_apre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ficha',
            old_name='num_matri',
            new_name='esta',
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='num_apre_forma',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='num_apre_pendi_regi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='num_apre_proce',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
