# Generated by Django 5.1.4 on 2025-01-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0043_rename_num_matri_t_ficha_esta_t_ficha_num_apre_forma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_prematri_docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('apren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre')),
                ('docu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu')),
            ],
            options={
                'db_table': 'T_prematri_docu',
                'managed': True,
            },
        ),
    ]
