# Generated by Django 5.1.4 on 2025-01-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0044_t_prematri_docu'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_prematri_docu',
            name='esta',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_prematri_docu',
            name='docu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu'),
        ),
    ]
