# Generated by Django 5.1.4 on 2025-01-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0045_t_prematri_docu_esta_alter_t_prematri_docu_docu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_docu',
            name='archi',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documentos'),
        ),
    ]
