# Generated by Django 5.1.4 on 2025-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0047_t_insti_edu_coordi_t_insti_edu_coordi_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_prematri_docu',
            name='vali',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
