# Generated by Django 5.1.4 on 2025-01-10 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0052_alter_t_prematri_docu_usr_apro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_insti_docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('esta', models.CharField(max_length=200)),
                ('vali', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_apro', models.DateField(blank=True, null=True)),
                ('fecha_carga', models.DateField(blank=True, null=True)),
                ('docu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_docu')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha')),
                ('usr_apro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_insti_aprobados', to=settings.AUTH_USER_MODEL)),
                ('usr_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_insti_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_insti_docu',
                'managed': True,
            },
        ),
    ]
