# Generated by Django 5.1.4 on 2025-01-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0053_t_insti_docu'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_progra',
            name='cod_prog',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_progra',
            name='nomd',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
