# Generated by Django 5.1.4 on 2025-01-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0054_t_progra_cod_prog_t_progra_nomd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_nove_ficha',
        ),
    ]
