# Generated by Django 5.1.4 on 2025-01-11 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0055_delete_t_nove_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_nove_ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha')),
                ('nove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_nove')),
            ],
            options={
                'db_table': 'T_nove_ficha',
                'managed': True,
            },
        ),
    ]
