# Generated by Django 5.1.4 on 2025-01-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0057_alter_t_munici_cod_munici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_insti_edu',
            name='depa',
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='cale',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='dane',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='gene',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='grados',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='jorna',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='lati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='longi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='num_sedes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_insti_edu',
            name='zona',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='coordi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='coordi_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='coordi_tele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='insti_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='pote_apre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='recto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='recto_tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
