# Generated by Django 5.1.4 on 2025-01-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0058_remove_t_insti_edu_depa_t_insti_edu_cale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_centro_forma',
            name='dire',
        ),
        migrations.RemoveField(
            model_name='t_centro_forma',
            name='muni',
        ),
        migrations.AddField(
            model_name='t_centro_forma',
            name='cod',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_centro_forma',
            name='depa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_departa'),
        ),
        migrations.AlterField(
            model_name='t_centro_forma',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
