# Generated by Django 5.1.4 on 2025-01-12 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0061_remove_t_insti_edu_gesto_t_gestor_insti_edu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_gestor',
            name='esta',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=200),
        ),
        migrations.CreateModel(
            name='T_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_apre_poten', models.CharField(max_length=5)),
                ('esta', models.CharField(max_length=20)),
                ('fecha_crea', models.DateTimeField()),
                ('fecha_modi', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_centro_forma')),
                ('insti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_insti_edu')),
            ],
            options={
                'db_table': 'T_grupo',
            },
        ),
        migrations.CreateModel(
            name='T_gestor_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField()),
                ('fecha_modi', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_gestor')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_grupo')),
            ],
            options={
                'db_table': 'T_gestor_grupo',
            },
        ),
        migrations.AddField(
            model_name='t_apre',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_grupo'),
        ),
    ]
