# Generated by Django 5.1.4 on 2025-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0063_rename_año_t_gestor_insti_edu_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_grupo',
            name='esta',
            field=models.CharField(max_length=100),
        ),
    ]
