# Generated by Django 5.1.4 on 2025-01-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0064_alter_t_grupo_esta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_prematri_docu',
            name='docu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu'),
        ),
    ]
