# Generated by Django 5.1.4 on 2025-01-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0065_alter_t_prematri_docu_docu'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grupo',
            name='progra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_progra'),
            preserve_default=False,
        ),
    ]
