# Generated by Django 5.1.4 on 2025-01-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0066_t_grupo_progra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_insti_docu',
            name='ficha',
        ),
        migrations.AddField(
            model_name='t_insti_docu',
            name='insti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_insti_edu'),
            preserve_default=False,
        ),
    ]
