# Generated by Django 5.1.4 on 2025-01-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0067_remove_t_insti_docu_ficha_t_insti_docu_insti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_insti_docu',
            name='docu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu'),
        ),
    ]
