# Generated by Django 5.1.4 on 2025-01-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0069_t_gestor_depa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='t_gestor_depa',
            name='fecha_crea',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_gestor_depa',
            name='usuario_crea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
