# Generated by Django 5.1.4 on 2025-01-15 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0070_t_gestor_depa_fecha_crea_t_gestor_depa_usuario_crea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_documento_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cate', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('esta', models.CharField(max_length=200)),
                ('docu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu')),
                ('usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_documento_laboral',
                'managed': True,
            },
        ),
    ]
