# Generated by Django 5.1.4 on 2025-01-15 18:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0071_t_documento_laboral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_documento_laboral',
            new_name='T_docu_labo',
        ),
        migrations.AlterModelTable(
            name='t_docu_labo',
            table='T_docu_labo',
        ),
    ]
