# Generated by Django 5.1.4 on 2025-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0072_rename_t_documento_laboral_t_docu_labo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_docu_labo',
            name='cate',
            field=models.CharField(choices=[('certificacion', 'Certificacion'), ('reconocimiento', 'Reconocimiento')], max_length=100),
        ),
    ]
