# Generated by Django 5.1.4 on 2025-01-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0074_t_docu_labo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_perfil')),
            ],
            options={
                'db_table': 'T_cuentas',
                'managed': True,
            },
        ),
    ]
