# Generated by Django 5.1.4 on 2025-01-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0075_t_cuentas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_cuentas',
            old_name='estado',
            new_name='esta',
        ),
    ]
