# Generated by Django 5.1.4 on 2025-01-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0077_t_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_oferta',
            old_name='decri',
            new_name='descri',
        ),
    ]
