# Generated by Django 5.1.4 on 2025-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0081_t_insti_edu_esta_docu'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_repre_legal',
            name='dni',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
