# Generated by Django 5.1.4 on 2025-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0082_t_repre_legal_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_insti_edu',
            name='cale',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=100),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='esta',
            field=models.CharField(choices=[('articulado', 'Articulado'), ('articulado nuevo', 'Articulado nuevo'), ('antiguo activo', 'Antiguo activo'), ('cierre temporal', 'Cierre temporal'), ('nuevo activo', 'Nuevo activo'), ('cierre definitivo', 'Cierre definitivo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='gene',
            field=models.CharField(choices=[('mi', 'Mixto'), ('ma', 'Masculino'), ('fe', 'Femenino')], max_length=100),
        ),
        migrations.AlterField(
            model_name='t_insti_edu',
            name='zona',
            field=models.CharField(choices=[('r', 'Rural'), ('u', 'Urbana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='t_perfil',
            name='dni',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='t_perfil',
            name='gene',
            field=models.CharField(choices=[('H', 'Masculino'), ('M', 'Femenino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='dni',
            field=models.BigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='paren',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo'), ('abuela', 'abuela'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('tio', 'tío'), ('tia', 'tía'), ('otro', 'Otro')], max_length=200),
        ),
    ]
