# Generated by Django 5.1.4 on 2025-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0083_alter_t_insti_edu_cale_alter_t_insti_edu_esta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_repre_legal',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
