# Generated by Django 5.1.4 on 2025-02-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0085_t_apre_usu_crea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_repre_legal',
            name='ciu',
        ),
        migrations.RemoveField(
            model_name='t_repre_legal',
            name='depa',
        ),
    ]
