# Generated by Django 5.1.4 on 2025-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0086_remove_t_repre_legal_ciu_remove_t_repre_legal_depa'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_oferta_instru',
            name='respuesta_rh',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
