# Generated by Django 5.1.4 on 2025-02-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0087_t_oferta_instru_respuesta_rh'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_contra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_contratacion', 'En Contratacion'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_contratacion', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('instru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='commons.t_instru')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='commons.t_oferta')),
                ('postu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='commons.t_oferta_instru')),
            ],
            options={
                'db_table': 't_contra',
                'managed': True,
            },
        ),
    ]
