# Generated by Django 5.1.4 on 2025-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0088_t_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_centro_forma',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
