# Generated by Django 5.1.4 on 2025-03-24 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0089_alter_t_centro_forma_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_insti_docu',
            name='fecha_apro',
        ),
        migrations.RemoveField(
            model_name='t_insti_docu',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='t_insti_docu',
            name='usr_apro',
        ),
        migrations.RemoveField(
            model_name='t_insti_docu',
            name='usr_carga',
        ),
        migrations.CreateModel(
            name='T_histo_docu_insti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('carga', 'Carga de documento'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('recarga', 'Recarga tras rechazo')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('docu_insti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_docu', to='commons.t_insti_docu')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_histo_docu_insti',
                'managed': True,
            },
        ),
    ]
