# Generated by Django 5.1.4 on 2025-03-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0090_remove_t_insti_docu_fecha_apro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_histo_docu_insti',
            old_name='accion',
            new_name='acci',
        ),
        migrations.RenameField(
            model_name='t_histo_docu_insti',
            old_name='comentario',
            new_name='comen',
        ),
        migrations.RenameField(
            model_name='t_histo_docu_insti',
            old_name='usuario',
            new_name='usu',
        ),
    ]
