# Generated by Django 5.1.4 on 2025-03-26 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0091_rename_accion_t_histo_docu_insti_acci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_prematri_docu',
            name='fecha_apro',
        ),
        migrations.RemoveField(
            model_name='t_prematri_docu',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='t_prematri_docu',
            name='usr_apro',
        ),
        migrations.RemoveField(
            model_name='t_prematri_docu',
            name='usr_carga',
        ),
        migrations.AlterField(
            model_name='t_histo_docu_insti',
            name='acci',
            field=models.CharField(choices=[('carga', 'Carga de documento'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('recarga', 'Recarga tras rechazo'), ('eliminacion', 'Eliminacion del documento')], max_length=20),
        ),
        migrations.CreateModel(
            name='T_histo_docu_prematri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acci', models.CharField(choices=[('carga', 'Carga de documento'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('recarga', 'Recarga tras rechazo'), ('eliminacion', 'Eliminacion del documento')], max_length=20)),
                ('comen', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('docu_prematri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_docu', to='commons.t_prematri_docu')),
                ('usu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_histo_docu_prematri',
                'managed': True,
            },
        ),
    ]
