# Generated by Django 5.1.4 on 2025-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0092_remove_t_prematri_docu_fecha_apro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_apre',
            name='esta_docu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
