# Generated by Django 5.1.4 on 2025-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0093_t_apre_esta_docu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_admin',
            name='area',
            field=models.CharField(choices=[('sistemas', 'Sistemas'), ('contable', 'Contable'), ('direccion', 'Dirección'), ('rrhh', 'RRHH')], max_length=200),
        ),
    ]
