# Generated by Django 5.1.4 on 2025-03-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0095_alter_t_perfil_tipo_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_perfil',
            name='tipo_dni',
            field=models.CharField(choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cedula de ciudadania'), ('pp', 'Pasaporte'), ('ce', 'Cedula de extranjeria')], max_length=50),
        ),
    ]
