# Generated by Django 5.1.4 on 2025-04-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0096_alter_t_perfil_tipo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ficha',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.t_grupo'),
            preserve_default=False,
        ),
    ]
