# Generated by Django 5.1.4 on 2025-04-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0097_t_ficha_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_documentfolder',
            name='iden',
        ),
        migrations.RemoveField(
            model_name='t_documentfolder',
            name='url',
        ),
        migrations.RemoveField(
            model_name='t_documentfolderaprendiz',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='t_documentfolderaprendiz',
            name='iden',
        ),
        migrations.RemoveField(
            model_name='t_documentfolderaprendiz',
            name='url',
        ),
        migrations.AddField(
            model_name='t_documentfolder',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu'),
        ),
        migrations.AddField(
            model_name='t_documentfolderaprendiz',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu'),
        ),
        migrations.AlterField(
            model_name='t_documentfolder',
            name='tipo',
            field=models.CharField(choices=[('documento', 'Documento'), ('carpeta', 'Carpeta')], default='carpeta', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_documentfolderaprendiz',
            name='tipo',
            field=models.CharField(choices=[('documento', 'Documento'), ('carpeta', 'Carpeta')], default='carpeta', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_ficha',
            name='instru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_instru'),
        ),
    ]
