# Generated by Django 5.1.4 on 2025-04-08 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0100_alter_t_crono_fecha_fin_acti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_cali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cali', models.CharField(max_length=5)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('acti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_acti_ficha')),
                ('apre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre')),
            ],
            options={
                'db_table': 't_cali',
                'managed': True,
            },
        ),
    ]
