# Generated by Django 5.1.4 on 2025-04-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0101_t_cali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acti',
            name='raps',
        ),
    ]
