# Generated by Django 5.1.4 on 2025-04-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0102_remove_t_acti_raps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_raps',
            name='fase',
        ),
    ]
