# Generated by Django 5.1.4 on 2025-04-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0103_remove_t_raps_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acti',
            name='horas_auto',
        ),
        migrations.RemoveField(
            model_name='t_acti',
            name='horas_dire',
        ),
    ]
