# Generated by Django 5.1.4 on 2025-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0104_remove_t_acti_horas_auto_remove_t_acti_horas_dire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_compe',
            name='fase',
            field=models.CharField(choices=[('analisis', 'Fase Analisis'), ('planeacion', 'Fase Planeacion'), ('ejecucion', 'Fase Ejecucion'), ('evaluacion', 'Fase Evaluacion')], max_length=200),
        ),
    ]
