# Generated by Django 5.1.4 on 2025-04-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0105_alter_t_compe_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_encu_apre',
            name='ficha',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha'),
            preserve_default=False,
        ),
    ]
