# Generated by Django 5.1.4 on 2025-04-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0107_t_encu_apre_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='encu',
        ),
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='apre',
        ),
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='ficha',
        ),
        migrations.DeleteModel(
            name='T_encu',
        ),
        migrations.DeleteModel(
            name='T_encu_apre',
        ),
    ]
