# Generated by Django 5.1.4 on 2025-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0109_t_encu_t_encu_apre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_encu',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='t_encu_apre',
            name='ficha',
        ),
        migrations.AlterField(
            model_name='t_encu',
            name='fase',
            field=models.CharField(choices=[('analisis', 'Fase Analisis'), ('planeacion', 'Fase Planeacion'), ('ejecucion', 'Fase Ejecucion'), ('evaluacion', 'Fase Evaluacion')], max_length=200),
        ),
    ]
