# Generated by Django 5.1.4 on 2025-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0110_remove_t_encu_guia_remove_t_encu_apre_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_instru',
            name='contra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_instru',
            name='tipo_vincu',
            field=models.CharField(choices=[('termino indefinido', 'Termino indefinido'), ('colaborador externo', 'Colaborador externo'), ('sindefinir', 'Sin definir')], max_length=50),
        ),
    ]
