# Generated by Django 5.1.4 on 2024-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_perfil',
            name='tipo_dni',
            field=models.CharField(blank=True, choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cedula de ciudadania'), ('pp', 'Pasaporte'), ('cc', 'Tarjeta de extranjeria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='t_perfil',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='t_perfil',
            name='tele',
            field=models.IntegerField(),
        ),
    ]
