# Generated by Django 5.1.4 on 2024-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_t_perfil_tipo_dni_alter_t_perfil_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_perfil',
            name='tele',
            field=models.CharField(max_length=100),
        ),
    ]
