# Generated by Django 5.1.4 on 2024-12-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_t_perfil_tele'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('esta', models.CharField(max_length=200)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.t_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='T_aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=200)),
                ('esta', models.CharField(max_length=200)),
                ('ficha', models.CharField(max_length=200)),
                ('insti', models.CharField(max_length=200)),
                ('repre_legal', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('prematricula', 'Pre matricula')], max_length=200)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.t_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='T_lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('esta', models.CharField(max_length=200)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.t_perfil')),
            ],
        ),
    ]
