# Generated by Django 5.1.4 on 2024-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
